{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e315def1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "! pip install transformers -U -q"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "27781ce9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: sentencepiece in c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (0.1.99)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "! pip install sentencepiece"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ed096fae",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "'grep' is not recognized as an internal or external command,\n",
      "operable program or batch file.\n"
     ]
    }
   ],
   "source": [
    "! pip freeze | grep transformers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "67cda6dd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "! pip install -q gradio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c9f86a38",
   "metadata": {},
   "outputs": [],
   "source": [
    "from transformers import MBartForConditionalGeneration, MBart50TokenizerFast"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "27b3dd2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = MBartForConditionalGeneration.from_pretrained(\"facebook/mbart-large-50-one-to-many-mmt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "8360d827",
   "metadata": {},
   "outputs": [],
   "source": [
    "tokenizer = MBart50TokenizerFast.from_pretrained(\"facebook/mbart-large-50-one-to-many-mmt\", src_lang=\"en_XX\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8517e69b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "C:\\Users\\modik\\AppData\\Local\\Temp\\ipykernel_18528\\3532741343.py:21: GradioUnusedKwargWarning: You have unused kwarg parameters in Audio, please remove them: {'sources': ['microphone']}\n",
      "  [\"state\", gr.Audio(sources=[\"microphone\"], streaming=True)],\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 426, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 84, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\applications.py\", line 1115, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 83, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 20, in __call__\n",
      "    raise e\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 17, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 274, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 193, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\to_thread.py\", line 33, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 877, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 807, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7864\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 426, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 84, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\applications.py\", line 1115, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 83, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 20, in __call__\n",
      "    raise e\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 17, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 274, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 193, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\to_thread.py\", line 33, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 877, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 807, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 426, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 84, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\applications.py\", line 1115, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 83, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 20, in __call__\n",
      "    raise e\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 17, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 274, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 193, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\to_thread.py\", line 33, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 877, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 807, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 426, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 84, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\applications.py\", line 1115, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 83, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 20, in __call__\n",
      "    raise e\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 17, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 274, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 193, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\to_thread.py\", line 33, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 877, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 807, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 426, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 84, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\applications.py\", line 1115, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 83, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 20, in __call__\n",
      "    raise e\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 17, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 274, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 193, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\to_thread.py\", line 33, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 877, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 807, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[1;32mIn [8]\u001b[0m, in \u001b[0;36m<cell line: 26>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     16\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m stream, transcriber({\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msampling_rate\u001b[39m\u001b[38;5;124m\"\u001b[39m: sr, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mraw\u001b[39m\u001b[38;5;124m\"\u001b[39m: stream})[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtext\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n\u001b[0;32m     19\u001b[0m demo \u001b[38;5;241m=\u001b[39m gr\u001b[38;5;241m.\u001b[39mInterface(\n\u001b[0;32m     20\u001b[0m     transcribe,\n\u001b[0;32m     21\u001b[0m     [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mstate\u001b[39m\u001b[38;5;124m\"\u001b[39m, gr\u001b[38;5;241m.\u001b[39mAudio(sources\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmicrophone\u001b[39m\u001b[38;5;124m\"\u001b[39m], streaming\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)],\n\u001b[0;32m     22\u001b[0m     [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mstate\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtext\u001b[39m\u001b[38;5;124m\"\u001b[39m],\n\u001b[0;32m     23\u001b[0m     live\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m,\n\u001b[0;32m     24\u001b[0m )\n\u001b[1;32m---> 26\u001b[0m \u001b[43mdemo\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mlaunch\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\blocks.py:2115\u001b[0m, in \u001b[0;36mBlocks.launch\u001b[1;34m(self, inline, inbrowser, share, debug, enable_queue, max_threads, auth, auth_message, prevent_thread_lock, show_error, server_name, server_port, show_tips, height, width, encrypt, favicon_path, ssl_keyfile, ssl_certfile, ssl_keyfile_password, ssl_verify, quiet, show_api, file_directories, allowed_paths, blocked_paths, root_path, _frontend, app_kwargs, state_session_capacity)\u001b[0m\n\u001b[0;32m   2107\u001b[0m \u001b[38;5;66;03m# If running in a colab or not able to access localhost,\u001b[39;00m\n\u001b[0;32m   2108\u001b[0m \u001b[38;5;66;03m# a shareable link must be created.\u001b[39;00m\n\u001b[0;32m   2109\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[0;32m   2110\u001b[0m     _frontend\n\u001b[0;32m   2111\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m wasm_utils\u001b[38;5;241m.\u001b[39mIS_WASM\n\u001b[0;32m   2112\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m networking\u001b[38;5;241m.\u001b[39murl_ok(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlocal_url)\n\u001b[0;32m   2113\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mshare\n\u001b[0;32m   2114\u001b[0m ):\n\u001b[1;32m-> 2115\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m   2116\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mWhen localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2117\u001b[0m     )\n\u001b[0;32m   2119\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mis_colab:\n\u001b[0;32m   2120\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m quiet:\n",
      "\u001b[1;31mValueError\u001b[0m: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 426, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 84, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\applications.py\", line 1115, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 83, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 20, in __call__\n",
      "    raise e\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 17, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 274, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fastapi\\routing.py\", line 193, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\to_thread.py\", line 33, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 877, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 807, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\users\\modik\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    }
   ],
   "source": [
    "import gradio as gr\n",
    "from transformers import pipeline\n",
    "import numpy as np\n",
    "\n",
    "transcriber = pipeline(\"automatic-speech-recognition\", model=\"openai/whisper-base.en\")\n",
    "\n",
    "def transcribe(stream, new_chunk):\n",
    "    sr, y = new_chunk\n",
    "    y = y.astype(np.float32)\n",
    "    y /= np.max(np.abs(y))\n",
    "\n",
    "    if stream is not None:\n",
    "        stream = np.concatenate([stream, y])\n",
    "    else:\n",
    "        stream = y\n",
    "    return stream, transcriber({\"sampling_rate\": sr, \"raw\": stream})[\"text\"]\n",
    "\n",
    "\n",
    "demo = gr.Interface(\n",
    "    transcribe,\n",
    "    [\"state\", gr.Audio(sources=[\"microphone\"], streaming=True)],\n",
    "    [\"state\", \"text\"],\n",
    "    live=True,\n",
    ")\n",
    "\n",
    "demo.launch()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bceb6c7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
